# Generated by Django 5.0.4 on 2024-04-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_homework_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_fininshed',
            new_name='is_finished',
        ),
    ]
